# Generated by Django 5.2.17 on 2026-09-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyStaffingNeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("count_needed", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nascar_race", "NASCAR race"),
                            ("rodeo", "Rodeo"),
                            ("skills_challenge", "Skills challenge"),
                            ("tradeshow", "Tradeshow"),
                            ("job_fair", "Job fair"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("event_type_custom", models.CharField(blank=True, max_length=255)),
                ("venue_name", models.CharField(blank=True, max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("state", models.CharField(blank=True, max_length=2)),
                ("zip", models.CharField(blank=True, max_length=10)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("setup_date", models.DateField(blank=True, null=True)),
                ("setup_arrival_time", models.TimeField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_date", models.DateField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("arrival_home_date", models.DateField(blank=True, null=True)),
                (
                    "staff_signup_deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="After this, staff can no longer submit or edit availability. Blank = no cutoff.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("upcoming", "Upcoming"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("contact_name", models.CharField(blank=True, max_length=255)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                (
                    "housing_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hotel", "Hotel"),
                            ("airbnb", "Airbnb"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("hotel_name", models.CharField(blank=True, max_length=255)),
                ("housing_address", models.CharField(blank=True, max_length=255)),
                ("housing_city", models.CharField(blank=True, max_length=120)),
                ("housing_state", models.CharField(blank=True, max_length=2)),
                ("housing_zip", models.CharField(blank=True, max_length=10)),
                (
                    "housing_info",
                    models.TextField(
                        blank=True,
                        help_text="WiFi network/password, check-out instructions, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="EventReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_leads", models.PositiveIntegerField(default=0)),
                ("qualified_leads", models.PositiveIntegerField(default=0)),
                (
                    "station_play_counts",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='e.g. {"excavator_simulator": 41, "kiosk_test": 141}',
                    ),
                ),
                ("is_finalized", models.BooleanField(default=False)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event_notes",
                    models.TextField(
                        blank=True,
                        help_text="Operational retrospective (e.g. staffing/logistics).",
                    ),
                ),
                (
                    "lead_notes",
                    models.TextField(
                        blank=True, help_text="Qualitative notes about the crowd/leads."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fuel", "Fuel"),
                            ("food", "Food"),
                            ("lodging", "Lodging"),
                            ("marketing", "Marketing"),
                            ("supplies", "Supplies"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                ("receipt_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("is_voided", models.BooleanField(default=False)),
                ("voided_reason", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
