# Generated by Django 5.2.17 on 2026-09-22 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("staffing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailystaffingneed",
            name="pay_role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="daily_needs",
                to="staffing.payrole",
            ),
        ),
        migrations.AddField(
            model_name="dailystaffingneed",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_needs",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="eventreport",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="events.event",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailystaffingneed",
            unique_together={("event", "date", "pay_role")},
        ),
    ]
