# Generated by Django 5.2.17 on 2026-09-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "buffer_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Days after end_date that data stays exclusive before becoming shareable.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("primary_contact_name", models.CharField(blank=True, max_length=255)),
                (
                    "primary_contact_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                ("primary_contact_phone", models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerViewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_customer_admin", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "includes_shared_pool",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this plan grants access to the broader shared dashboard, in addition to the customer's own exclusive events.",
                    ),
                ),
                (
                    "detail_level",
                    models.CharField(
                        choices=[
                            ("aggregate", "Aggregate stats only"),
                            ("anonymized", "Anonymized profiles"),
                            ("full_contact", "Full contact details"),
                        ],
                        default="anonymized",
                        max_length=20,
                    ),
                ),
                (
                    "monthly_record_cap",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("allows_export", models.BooleanField(default=False)),
                (
                    "industry_filter",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated, optional.",
                        max_length=255,
                    ),
                ),
                (
                    "region_filter",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated, optional.",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
