# Generated by Django 5.2.17 on 2026-09-22 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="events",
            field=models.ManyToManyField(
                blank=True,
                help_text="Events explicitly tied to this agreement (in addition to any date-range auto-assignment your event-creation flow adds).",
                related_name="agreements",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agreements",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="customerviewer",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invited_viewers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customerviewer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="viewer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agreements",
                to="customers.plan",
            ),
        ),
    ]
