# Generated by Django 5.2.17 on 2026-09-22 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("kiosk_test", "Kiosk test"),
                            ("hunting_game", "Hunting game"),
                            ("simulator", "Heavy equipment simulator"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_rebuilt_in_house",
                    models.BooleanField(
                        default=False,
                        help_text="True for the kiosk test and hunting game; false for simulators, which stay third-party and are integrated via a station agent.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("passed", models.BooleanField(blank=True, null=True)),
                (
                    "answers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Kiosk test answers, if applicable.",
                    ),
                ),
                (
                    "raw_source_row",
                    models.JSONField(
                        blank=True,
                        help_text="For simulator results ingested from the CSV station agent - the original row, unparsed fields kept for audit.",
                        null=True,
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_results",
                        to="participants.attendance",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="stations.station",
                    ),
                ),
            ],
        ),
    ]
